import { HomeForm } from "@/components/home-form"
import { BriefcaseBusinessIcon, Github } from "lucide-react"

export default function HomePage() {
  return (
    <div 
      className="min-h-screen max-w-screen bg-cover bg-center bg-no-repeat flex flex-col items-center justify-center p-8 pb-0 overflow-x-hidden"
      style={{ backgroundImage: `url('/gradii-image.png')` }}
    >
      <div className="container mx-auto px-4 py-20">
        <div className="max-w-3xl mx-auto text-center">
          {/* Header Section */}
          <div className="mb-16">
            <h1 className="text-5xl font-bold bg-gradient-to-r from-neutral-900 via-neutral-700 to-neutral-600 dark:from-white dark:via-neutral-200 dark:to-neutral-400 bg-clip-text text-transparent mb-6">
              GitHub README Generator
            </h1>
            <p className="text-xl text-neutral-600 dark:text-neutral-300 max-w-2xl mx-auto leading-relaxed">
              Transform your repositories with professional, comprehensive README files generated by advanced AI in seconds
            </p>
          </div>

          {/* Form Container */}
          <div className="bg-white/70 dark:bg-neutral-800/50 backdrop-blur-xl rounded-2xl shadow-xl border border-neutral-200/50 dark:border-neutral-700/50 p-10">
            <HomeForm />
          </div>

          {/* Features Section */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-16">
            <div className="text-center p-6 rounded-xl bg-white/50 dark:bg-neutral-800/30 border border-neutral-200/30 dark:border-neutral-700/30">
              <div className="w-12 h-12 bg-blue-100 dark:bg-blue-900/30 rounded-xl flex items-center justify-center mx-auto mb-4">
                <svg className="w-6 h-6 text-blue-600 dark:text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                </svg>
              </div>
              <h3 className="font-semibold text-neutral-900 dark:text-white mb-2">Lightning Fast</h3>
              <p className="text-sm text-neutral-600 dark:text-neutral-400">Generate comprehensive READMEs in seconds with AI</p>
            </div>
            <div className="text-center p-6 rounded-xl bg-white/50 dark:bg-neutral-800/30 border border-neutral-200/30 dark:border-neutral-700/30">
              <div className="w-12 h-12 bg-green-100 dark:bg-green-900/30 rounded-xl flex items-center justify-center mx-auto mb-4">
                <svg className="w-6 h-6 text-green-600 dark:text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
              <h3 className="font-semibold text-neutral-900 dark:text-white mb-2">Smart Analysis</h3>
              <p className="text-sm text-neutral-600 dark:text-neutral-400">AI analyzes your code structure and dependencies</p>
            </div>
            <div className="text-center p-6 rounded-xl bg-white/50 dark:bg-neutral-800/30 border border-neutral-200/30 dark:border-neutral-700/30">
              <div className="w-12 h-12 bg-purple-100 dark:bg-purple-900/30 rounded-xl flex items-center justify-center mx-auto mb-4">
                <BriefcaseBusinessIcon className="text-purple-900" />
              </div>
              <h3 className="font-semibold text-neutral-900 dark:text-white mb-2">Professional</h3>
              <p className="text-sm text-neutral-600 dark:text-neutral-400">Clean, structured, and documentation best practices</p>
            </div>
          </div>
        </div>
      </div>

      <div className="border-t py-4 border-neutral-500 w-screen px-4">
        <div className="flex w-full justify-between">
          <div className="text-neutral-500">
            © 2025 ReadmeX — All rights reserved.
          </div>
          <div className="flex gap-1">
            <a
              className="text-neutral-500"
              target="_blank"
              href="https://github.com/michael-020"
            >
              <Github className="size-6" />
            </a>
            <a 
              href="https://x.com/MichaelHosamani"
              target="_blank"
            >
              <svg xmlns="http://www.w3.org/2000/svg" stroke="#737373" x="0px" y="0px" width="28px" height="28px" viewBox="0 0 30 30">
                <path d="M26.37,26l-8.795-12.822l0.015,0.012L25.52,4h-2.65l-6.46,7.48L11.28,4H4.33l8.211,11.971L12.54,15.97L3.88,26h2.65 l7.182-8.322L19.42,26H26.37z M10.23,6l12.34,18h-2.1L8.12,6H10.23z"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
  )
}