"use client"

import { HomeForm } from "@/components/home-form"
import { BriefcaseBusinessIcon, Github } from "lucide-react"
import { motion } from "framer-motion"

export default function HomePage() {
  return (
    <div 
      className="min-h-screen max-w-screen bg-cover bg-center bg-no-repeat flex flex-col items-center justify-center p-4 sm:p-6 lg:p-8 sm:pb-0 lg:pb-0 pb-0 overflow-x-hidden"
      style={{ backgroundImage: `url('/gradii-image.png')` }}
    >
      <div className="container mx-auto px-2 sm:px-4 py-8 sm:py-12 lg:py-20 w-full">
        <div className="max-w-3xl mx-auto text-center">
          <motion.div 
            className="mb-8 sm:mb-12 lg:mb-16 px-2"
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: "easeInOut" }}
          >
            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold bg-gradient-to-r from-neutral-100 via-neutral-200 to-neutral-400 bg-clip-text text-transparent mb-4 sm:mb-6 leading-tight">
              GitHub README Generator
            </h1>
            <p className="text-base sm:text-lg lg:text-xl text-neutral-400 max-w-2xl mx-auto leading-relaxed px-2">
              Transform your repositories with professional, comprehensive README files generated by advanced AI in seconds
            </p>
          </motion.div>

          <motion.div 
            className="bg-neutral-800/50 backdrop-blur-xl rounded-xl sm:rounded-2xl shadow-xl border border-neutral-700/50 p-4 sm:p-6 lg:p-10 mx-2 sm:mx-0"
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: "easeInOut" }}
          >
            <HomeForm />
          </motion.div>

          <motion.div 
            className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 sm:gap-6 lg:gap-8 mt-8 sm:mt-12 lg:mt-16 px-2 sm:px-0"
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: "easeInOut" }}
          >
            <div className="text-center p-4 sm:p-6 rounded-xl bg-neutral-800/30 border border-neutral-700/30">
              <div className="w-10 h-10 sm:w-12 sm:h-12 bg-blue-900/30 rounded-xl flex items-center justify-center mx-auto mb-3 sm:mb-4">
                <svg className="w-5 h-5 sm:w-6 sm:h-6 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                </svg>
              </div>
              <h3 className="font-semibold text-sm sm:text-base text-white mb-2">Lightning Fast</h3>
              <p className="text-xs sm:text-sm text-neutral-400">Generate comprehensive READMEs in seconds with AI</p>
            </div>
            <div className="text-center p-4 sm:p-6 rounded-xl bg-neutral-800/30 border border-neutral-700/30">
              <div className="w-10 h-10 sm:w-12 sm:h-12 bg-green-900/30 rounded-xl flex items-center justify-center mx-auto mb-3 sm:mb-4">
                <svg className="w-5 h-5 sm:w-6 sm:h-6 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
              <h3 className="font-semibold text-sm sm:text-base text-white mb-2">Smart Analysis</h3>
              <p className="text-xs sm:text-sm text-neutral-400">AI analyzes your code structure and dependencies</p>
            </div>
            <div className="text-center p-4 sm:p-6 rounded-xl bg-neutral-800/30 border border-neutral-700/30 sm:col-span-2 md:col-span-1">
              <div className="w-10 h-10 sm:w-12 sm:h-12 bg-purple-900/30 rounded-xl flex items-center justify-center mx-auto mb-3 sm:mb-4">
                <BriefcaseBusinessIcon className="text-purple-400 w-5 h-5 sm:w-6 sm:h-6" />
              </div>
              <h3 className="font-semibold text-sm sm:text-base text-white mb-2">Professional</h3>
              <p className="text-xs sm:text-sm text-neutral-400">Clean, structured, and documentation best practices</p>
            </div>
          </motion.div>
        </div>
      </div>

      <div className="border-t py-3 sm:py-4 border-neutral-500 w-screen px-4 sm:px-6">
        <div className="flex flex-col sm:flex-row w-full justify-between items-center gap-3 sm:gap-0">
          <div className="text-neutral-500 text-xs sm:text-sm text-center sm:text-left">
            © 2025 ReadmeX — All rights reserved.
          </div>
          <div className="flex gap-2 sm:gap-1.5">
            <a
              className="text-neutral-500 hover:text-neutral-300 transition-colors"
              target="_blank"
              href="https://github.com/michael-020/Readme-generator"
            >
              <Github className="size-5 sm:size-6" />
            </a>
            <a 
              href="https://x.com/MichaelHosamani"
              target="_blank"
              className="text-neutral-500 hover:text-neutral-300 transition-colors"
            >
              <svg xmlns="http://www.w3.org/2000/svg" stroke="currentColor" x="0px" y="0px" width="24px" height="24px" className="sm:w-7 sm:h-7" viewBox="0 0 30 30">
                <path d="M26.37,26l-8.795-12.822l0.015,0.012L25.52,4h-2.65l-6.46,7.48L11.28,4H4.33l8.211,11.971L12.54,15.97L3.88,26h2.65 l7.182-8.322L19.42,26H26.37z M10.23,6l12.34,18h-2.1L8.12,6H10.23z"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
  )
}
