import { HomeForm } from "@/components/home-form"
import { BriefcaseBusinessIcon } from "lucide-react"

export default function HomePage() {
  return (
    <div 
    className="min-h-screen bg-cover bg-center bg-no-repeat flex items-center justify-center p-8"
      style={{ backgroundImage: `url('/gradii-image.png')` }}
    >
      <div className="container mx-auto px-4 py-20">
        <div className="max-w-3xl mx-auto text-center">
          {/* Header Section */}
          <div className="mb-16">
            <h1 className="text-5xl font-bold bg-gradient-to-r from-neutral-900 via-neutral-700 to-neutral-600 dark:from-white dark:via-neutral-200 dark:to-neutral-400 bg-clip-text text-transparent mb-6">
              GitHub README Generator
            </h1>
            <p className="text-xl text-neutral-600 dark:text-neutral-300 max-w-2xl mx-auto leading-relaxed">
              Transform your repositories with professional, comprehensive README files generated by advanced AI in seconds
            </p>
          </div>

          {/* Form Container */}
          <div className="bg-white/70 dark:bg-neutral-800/50 backdrop-blur-xl rounded-2xl shadow-xl border border-neutral-200/50 dark:border-neutral-700/50 p-10">
            <HomeForm />
          </div>

          {/* Features Section */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-16">
            <div className="text-center p-6 rounded-xl bg-white/50 dark:bg-neutral-800/30 border border-neutral-200/30 dark:border-neutral-700/30">
              <div className="w-12 h-12 bg-blue-100 dark:bg-blue-900/30 rounded-xl flex items-center justify-center mx-auto mb-4">
                <svg className="w-6 h-6 text-blue-600 dark:text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                </svg>
              </div>
              <h3 className="font-semibold text-neutral-900 dark:text-white mb-2">Lightning Fast</h3>
              <p className="text-sm text-neutral-600 dark:text-neutral-400">Generate comprehensive READMEs in seconds with AI</p>
            </div>
            <div className="text-center p-6 rounded-xl bg-white/50 dark:bg-neutral-800/30 border border-neutral-200/30 dark:border-neutral-700/30">
              <div className="w-12 h-12 bg-green-100 dark:bg-green-900/30 rounded-xl flex items-center justify-center mx-auto mb-4">
                <svg className="w-6 h-6 text-green-600 dark:text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
              <h3 className="font-semibold text-neutral-900 dark:text-white mb-2">Smart Analysis</h3>
              <p className="text-sm text-neutral-600 dark:text-neutral-400">AI analyzes your code structure and dependencies</p>
            </div>
            <div className="text-center p-6 rounded-xl bg-white/50 dark:bg-neutral-800/30 border border-neutral-200/30 dark:border-neutral-700/30">
              <div className="w-12 h-12 bg-purple-100 dark:bg-purple-900/30 rounded-xl flex items-center justify-center mx-auto mb-4">
                <BriefcaseBusinessIcon className="text-purple-900" />
              </div>
              <h3 className="font-semibold text-neutral-900 dark:text-white mb-2">Professional</h3>
              <p className="text-sm text-neutral-600 dark:text-neutral-400">Clean, structured, and documentation best practices</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}